a = ['1', '2', '3']

print(', '.join(a))

#pymysql.err.IntegrityError: (1062, "Duplicate entry '5' for key 'PRIMARY'") отработать исключение
